name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Cypress run in Electron
        uses: cypress-io/github-action@v2.9.7
        with:
          group: Electron

      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          group: Chrome
      
      - name: Cypress run in Edge
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: edge
          group: Edge

