name: CI

on:
  push:
  workflow_dispatch:

jobs:
  cypress-electron-chrome-firefox:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: user --1001  
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Cypress run in Electron
        uses: cypress-io/github-action@v2.9.7

      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          
      - name: Cypress run in Firefox
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: firefox
    
  cypress-window:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Cypress run in Edge
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: edge

