name: CI

on:
  push:
  workflow_dispatch:

jobs:
  cypress-electron-chrome:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Cypress run in Electron
        uses: cypress-io/github-action@4

      - name: Cypress run in Chrome
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
    
  cypress-window:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Cypress run in Edge
        uses: cypress-io/github-action@v4
        with:
          browser: edge

